/****** Object:  Table [CURATED].[CREDIT_TRANSACTIONS]    Script Date: 16-02-2025 22:31:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CURATED].[CREDIT_TRANSACTIONS](
	[TRANSACTION_ID] [nvarchar](max) NULL,
	[CUSTOMER_ID] [nvarchar](max) NULL,
	[TRANSACTION_CITY_ID] [int] NULL,
	[AMOUNT] [real] NULL,
	[PAYMENT_TYPE] [nvarchar](max) NULL,
	[STATUS] [nvarchar](max) NOT NULL,
	[TRANSACTION_DATE] [nvarchar](max) NULL,
	[CUSTOMER_CITY_ID] [int] NULL,
	[CITY_ID_TO] [int] NULL,
	[TRANSACTION_DISTANCE] [real] NULL,
	[FRAUD_CRITICALITY] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

