--Top 10 Cities of High Fraud Criticality
SELECT TOP 10
    c.CITY_NAME,
    COUNT(*) AS HIGH_CRITICAL_ALERT_COUNT
from CURATED.CREDIT_TRANSACTIONS tr
    LEFT JOIN
    (SELECT DISTINCT CITY_ID, CITY_NAME FROM CURATED.CITY_DISTANCE) c
        ON (tr.TRANSACTION_CITY_ID = c.CITY_ID)
WHERE FRAUD_CRITICALITY = 'HIGH'
GROUP BY c.CITY_NAME
ORDER BY COUNT(*) DESC,
         MAX(tr.TRANSACTION_DATE) DESC