--Pie chart showing Fraud criticality trend
SELECT FRAUD_CRITICALITY,
       COUNT(*) AS CRITICALITY_COUNT
FROM CURATED.CREDIT_TRANSACTIONS
WHERE FRAUD_CRITICALITY != 'NIL'
GROUP BY FRAUD_CRITICALITY
ORDER BY COUNT(*) DESC