--Top 10 Customers of High Fraud Criticality
SELECT TOP 10
    c.CUSTOMER_ID,
    c.NAME,
    COUNT(*) AS HIGH_CRITICAL_ALERT_COUNT
from CURATED.CREDIT_TRANSACTIONS tr
    LEFT JOIN CURATED.CUSTOMER c
        ON (tr.CUSTOMER_ID = c.CUSTOMER_ID)
WHERE FRAUD_CRITICALITY = 'HIGH'
GROUP BY c.CUSTOMER_ID,
         c.NAME
ORDER BY COUNT(*) DESC,
         MAX(tr.TRANSACTION_DATE) DESC