--Bar chart displaying Fraud Alert Counts for past 12 months
SELECT 
    a.TRANSACTION_DATE_YEAR,
    a.TRANSACTION_DATE_MONTH,
    COALESCE(b.CRITICALITY_COUNT, 0) AS CRITICALITY_COUNT
FROM 
    (SELECT DISTINCT 
        YEAR(TRANSACTION_DATE) AS TRANSACTION_DATE_YEAR, 
        MONTH(TRANSACTION_DATE) AS TRANSACTION_DATE_MONTH 
     FROM CURATED.CREDIT_TRANSACTIONS 
     WHERE TRANSACTION_DATE > DATEADD(YEAR, -1, CURRENT_DATE)) a
LEFT JOIN 
    (SELECT 
        YEAR(TRANSACTION_DATE) AS TRANSACTION_DATE_YEAR, 
        MONTH(TRANSACTION_DATE) AS TRANSACTION_DATE_MONTH, 
        COUNT(*) AS CRITICALITY_COUNT
     FROM CURATED.CREDIT_TRANSACTIONS 
     WHERE TRANSACTION_DATE > DATEADD(YEAR, -1, CURRENT_DATE) 
     AND FRAUD_CRITICALITY != 'NIL'
     GROUP BY YEAR(TRANSACTION_DATE), MONTH(TRANSACTION_DATE)) b
ON 
    a.TRANSACTION_DATE_YEAR = b.TRANSACTION_DATE_YEAR 
    AND a.TRANSACTION_DATE_MONTH = b.TRANSACTION_DATE_MONTH
ORDER BY 
    a.TRANSACTION_DATE_YEAR DESC, a.TRANSACTION_DATE_MONTH DESC;